name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Obtener el código de la rama
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Paso 3: Copiar los archivos del frontend a la raíz del repositorio
      - name: Copy frontend content to root
        run: |
          if [ -d "frontend" ]; then
            echo "La carpeta 'frontend' existe, moviendo archivos..."
            cp -r frontend/* .  # Mueve todo el contenido de 'frontend' a la raíz
          else
            echo "La carpeta 'frontend' no existe o está vacía."
            exit 1
          fi

      # Paso 4: Subir el contenido como artefacto para GitHub Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Subir todos los archivos de la raíz

      # Paso 5: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
